baseURL = ""
languageCode = "en-us"
title = "Hana på norsk"
theme = "lanyon-hugo"
publishDir = "docs"
googleAnalytics = "UA-150529309-3"

[params]
	colorScheme = "scheme-darkbrown"
	DateFormat = "2 Jan 2006"
	description = ""
	sidebarDescription = ""
	sidebarFreeText = ""
